# Generated by Django 2.0 on 2017-11-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis', models.TextField(default='', verbose_name='mis')),
                ('anonymous', models.TextField(default='', verbose_name='anonymous')),
                ('time', models.TextField(default='', verbose_name='time')),
            ],
        ),
    ]
